### ISSUE TITLE
Arduino (ARM) compatibility

### ISSUE THREAD

**Issue by Novators** [Novators/libsqrl#11]
- EnScrypt requires too much RAM, and must be disabled
- Memory locking is not applicable, disable it

**Comment by ramriot** [comment]
Good choose, it will in any case not be a part of my API.

**Comment by Novators** [comment]
Also:
- Our entropy engine won't work in this environment.  Replace for embedded platforms.

**Comment by Novators** [comment]
Compiles, but untested.  Closing.
