### ISSUE TITLE
DLL_PUBLIC missing on several functions

### ISSUE THREAD

**Issue by Samulus** [Novators/libsqrl#31]
Hi there,

I was interested in running a Python based sqrl client using cffi + this library, but several of the functions that I want to utilize (like ``sqrl_user_create()`` in ``user.c``) are missing the DLL_PUBLIC flag above their prototypes. Are these functions missing the DLL_PUBLIC annotation intentionally? I can submit a pull request with the DLL_PUBLIC annotations present on the functions missing it if necessary, thanks.

**Comment by Novators** [comment]
Hi Samulus,

That function, and many like it, are not intended for direct use by clients.  The functions that are meant to be exposed are described in sqrl_client.h and sqrl_expert.h.  There is a "transaction" system to ensure that operations like this have all the data they need and clean up their memory when finished.

To create a new user, you would call:  `sqrl_client_begin_transaction( SQRL_TRANSACTION_IDENTITY_GENERATE, null, null, 0 );`

I'm hoping to get some better documentation written on this soon.

**Comment by Samulus** [comment]
Great thanks!
